### ISSUE TITLE
Dynamic Labels not working.

### ISSUE THREAD

**Issue by JRHutson** [JRHutson/Food-Resource-Map#9]
Trying to get if statement in lines 99 - 105 of index2.html to determine attribute field based on "current" and "next" variables. Currently do not receive any errors when running script, but all points return false and default to the else case.

**Comment by JRHutson** [comment]
@jgravios If you can provide any input it would be appreciated.

**Comment by JRHutson** [comment]
@jgravois If you have any input on this issue it would be appreciated.

**Comment by jgravois** [comment]
as you said, `current` and `next` are variables in your application, not attributes listed in your feature service [metadata](http://services6.arcgis.com/khUjDuArRH761yYG/arcgis/rest/services/FoodPantriesMaster/FeatureServer/0).

because of this, you'll need to write some conditional logic to compare one or more of your feature's actual properties to your variables in order to help define the appropriate symbology.

``` js
if (current === geojson.properties.FIELDNAME) {
  // assign appropriate marker
}
```

happy to help more if you get stuck.

**Comment by JRHutson** [comment]
Can I use FIELDNAME as an open ended parameter like that or are you putting it in the place of an actual field name?

If it can be open ended, I need two steps of logic then. First to find the fields that match current and next, then to determine whether the attribute is equal to True for those fields. 

If that isn't how it works I will have to rethink the logic behind this.

**Comment by jgravois** [comment]
> are you putting it in the place of an actual field name?

yes.  you're just introspecting the individual geojson features here.

**Comment by JRHutson** [comment]
The service has attribute fields that are named numerically based on the week and day. For each of the features those attributes are either "True" or "False" depending on whether the pantry distributes on a particular day. For example, if they distribute on the 1st Sunday of the month then field "10" would contain "True". 

From what I'm understanding, my intended methodology will not work. My hope was that a variable could be used to define the Attribute Field that determines the symbol used. If I can't use a variable to define the attribute field then I'll have to figure out another way of doing this.

**Comment by jgravois** [comment]
ohhh.  _now_ i understand what you're trying to do.
you just need to switch to [bracket notation](http://stackoverflow.com/questions/4968406/javascript-property-access-dot-notation-vs-brackets).

``` js
// dot notation
JSObjectLiteral.property

//bracket notation
ObjectLiteral['property']

// example (with variable substitution)
var myGeoJSON = {};
myGeoJSON.myfieldname = 'the value stored in the field for a single feature';
var fieldNameVariable = 'myfieldname'

yourGeoJSON[fieldNameVariable]  // not a string, the actual variable you want to substitute
>> "the value stored in the field for a single feature"
```

**Comment by JRHutson** [comment]
Awesome. Glad to know it can work. Headed out but I'll take a look at it soon and see if I can sort it out. 

Appreciate the help.

**Comment by JRHutson** [comment]
@jgravois I've tried applying it in the index3 file. At this point I'm not getting any error in the HTML but the console is giving me an error in the featurelayer.js. Any ideas on what is not being fed into the script so that it gives the undefined error?
<img width="1431" alt="screen shot 2015-09-12 at 9 38 10 am" src="https://cloud.githubusercontent.com/assets/10876900/9832530/40c6a2c0-5932-11e5-979a-58bbd9e498c3.png">

**Comment by jgravois** [comment]
if you set a breakpoint in your own code you can see that the variables you assign to `foodbankproxy[current]` and `foodbankproxy[next]` are undefined, (which causes more errors downstream).

check out the sample [here](https://dl.dropboxusercontent.com/u/59331579/js/regan.html) to see my working changes in action.

#### what i did
- modified the JSON bracket notation to inspect individual GeoJSON object properties.
- added an `else` block and wrapped both conditional blocks in curly braces since they spanned more than one line (this resolved the error being thrown in the console)
- recased the string match to `"TRUE"` (because its case sensitive).

if you aren't already, i highly recommend that you start trying to get comfortable with setting breakpoints at individual lines of interest and typing interactively in the console to see what is currently held in variables and objects, what's defined and what's not.  doing so has helped me own web development immensely.

holler if you have any more questions.
